const BasePath = "http://18.118.184.156/";

const ApisPath = {
    ApiRegisterUser:`${BasePath}api/users/register`,
    ApiLoginUser:`${BasePath}api/users/login`,
    ApiGetProfile:`${BasePath}api/users/get_profile`,
    ApiSendVerificationEmail: `${BasePath}api/users/send_verification_email`,
    ApiVerifyEmail: `${BasePath}api/users/verify_email`,
    ApiCheckEmailExistance: `${BasePath}api/users/email_exists`,
    ApiResetPassword: `${BasePath}api/users/update_password`,
    ApiSendResetCode: `${BasePath}api/users/send_reset_email`,
    ApiUploadIntroVideo: `${BasePath}api/media/upload_intro_video`,
    ApiUploadMedia: `${BasePath}api/media/upload_user_media`,
    ApiDeleteMedia: `${BasePath}api/media/delete_media`,
    ApiUpdateProfile: `${BasePath}api/users/update_profile`,
    ApiGetProfileLikes: `${BasePath}api/users/get_profile_likes`,
    ApiGetDiscover: `${BasePath}api/users/discover`,
    ApiLikeProfile: `${BasePath}api/users/like_profile`,
    ApiGetQuestions: `${BasePath}api/users/questions`,
    ApiAddAnswer: `${BasePath}api/media/answer_question`,
    ApiSocialLogin: `${BasePath}api/users/social_login`,
    ApiGetDates: `${BasePath}api/admin/dates/get_date_places`,
    ApiGetMyMatche: `${BasePath}api/users/my_matches`,
    ApiBookDate: `${BasePath}api/admin/dates/book_date`,
    ApiGetNotifications: `${BasePath}api/users/get_notifications`,
    ApiGetMessagesList: `${BasePath}api/chat/chats_list`,
    ApiGetMessages: `${BasePath}api/chat/get_messages`,
    ApiCreateChat: `${BasePath}api/chat/create_chat`,
    ApiSendMessage: `${BasePath}api/chat/send_message`,
    ApiChangePassword: `${BasePath}api/users/change_password`,
    ApiDeleteIntro: `${BasePath}api/media/delete_intro`,
    ApiSenMedia: `${BasePath}api/chat/send_media_message`,
    ApiGetDateCategories: `${BasePath}api/admin/dates/get_categories`,
    ApiInviteDateViaEmail: `${BasePath}api/admin/dates/invite_to_date_email`,
    ApiBlockUser: `${BasePath}api/users/block_user`,
    ApiReportUser: `${BasePath}api/users/report_user`,
    ApiSendFeedback: `${BasePath}api/users/send_feedback`,
    ApiDeleteAnswer: `${BasePath}api/users/delete_answer`,
    ApiReadAll: `${BasePath}api/chat/read_all`,
    ApiReviewDatePlace: `${BasePath}api/admin/dates/review_date_place`,
    ApiStoreReceit: `${BasePath}api/users/store_receipt`,
    ApiValidatePurchase: `${BasePath}api/users/validate_purchase`,
    ApiGetDateDetails: `${BasePath}api/admin/dates/get_date_detail`
}

export default ApisPath;
